<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Welcome to Solid</title>
  <style>
  #prototype {
    margin : 2em;
    padding : 1em;
  }
  #prototype input {
    margin : 1em;
    padding : 0.5em !important;
  }
  #loginStatusArea {
    float:right;
    clear:right;
    margin-top:-5em;
  }
  </style>
  <script>
    document.addEventListener('DOMContentLoaded', async function() {
      if (!UI.authn.currentUser()) await UI.authn.checkUser();
      let user = UI.authn.currentUser();
      if( user ) {
        document.getElementById('prototype').style.display = "none";
        var podRoot = user.uri.replace(/profile.*$/,'');
        podRoot = UI.rdf.sym(podRoot)
        panes.runDataBrowser();
        var outliner = panes.getOutliner(document)
        outliner.GotoSubject(podRoot, true, undefined, true, undefined)  
      }
      else {
        document.getElementById('prototype').style.display = "block";
        document.getElementById('loginStatusArea').appendChild(UI.authn.loginStatusBox(document, null, {}))

      }     
    })
  </script>
  <link href="/mash.css" rel="stylesheet"> 
</head>

<body class="db-layout">

<div id="prototype" class="container">
  <div class="page-header">
    <h1>Welcome to the Solid Prototype</h1>
    <div id="loginStatusArea" class="pull-right"></div>
  </div>

  <p class="lead">
    This is a prototype implementation of a Solid server.

    It is a fully functional server, but there are no security or stability guarantees.

    If you have not already done so, please create an account.
  </p>

<h2>Extended Information</h2>
<p class="lead">- <a href="https://solidproject.org">Solid Project Site</a></p>
<p class="lead">- <a href="https://github.com/solid">Solid Github Site</a></p>

  <section>
    {{#if serverLogo}}
    <img src="{{serverLogo}}" />
    {{/if}}
    <h2>Server info</h2>
    <dl>
      <dt>Name</dt>
      <dd>solidweb.org</dd>
      <dt>Description</dt>
      <dd>an experimental Solid Server</dd>
      <dt>Details</dt>
      <dd>Running on <a href="https://www.w3.org/community/solid/wiki/">Solid 5.6.9-beta</a></dd>
      <dt>Support</dt>
      <dd><a href="https://gitlab.com/solidweb.org/support">Gitlab Support Group</a></dd>
      <dd><a href="https://gitter.im/solidweb-org/community">Gitter Support Chat</a></dd>
      <dt>Terms and Conditions</dt>
      <dd><a href="https://serverproject.de/files/solidweb_org_terms.txt">./terms.txt</a></dd>
      <dt>Documentation</dt>
      <dd><a href="https://gist.github.com/ewingson/c6e97a996aa51eac9f7fd1b7eaf14dc4">How it's done</a></dd>
      <dt>License</dt>
      <dd><a href="https://github.com/ewingson/solidweb.org/blob/master/LICENSE">MIT</a></dd>
    </dl>
  </section>
</div>
  
  <header class="db-layout__header header" id="PageHeader"></header>
<div class="TabulatorOutline db-layout__content" id="DummyUUID" role="main">
  <table id="outline"></table>
  <div id="GlobalDashboard"></div>
</div>
<footer class="db-layout__footer" id="PageFooter"></footer>

<script src="/mashlib.js"></script>

</body>
</html>
